// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function Component1(Props) {
  var message = Props.message;
  return React.createElement("div", {
              onClick: (function (_event) {
                  console.log("clicked!");
                  return /* () */0;
                })
            }, message);
}

var make = Component1;

export {
  make ,
  
}
/* react Not a pure module */
