// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as VendoredArray$ReactTemplate from "./VendoredArray.js";

console.log(VendoredArray$ReactTemplate.get(/* array */[3], 0));

export {
  
}
/*  Not a pure module */
