// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


console.log("hello");

function f0(param) {
  console.log("f0");
  return /* () */0;
}

function f1(param) {
  console.log("f0");
  return /* () */0;
}

function f2(param) {
  console.log("f0");
  return /* () */0;
}

function f3(param) {
  console.log("f0");
  return /* () */0;
}

function f4(param) {
  console.log("f0");
  return /* () */0;
}

function f5(param) {
  console.log("f0");
  return /* () */0;
}

function f6(param) {
  console.log("f0");
  return /* () */0;
}

function f7(param) {
  console.log("f0");
  return /* () */0;
}

export {
  f0 ,
  f1 ,
  f2 ,
  f3 ,
  f4 ,
  f5 ,
  f6 ,
  f7 ,
  
}
/*  Not a pure module */
